AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'lib/tasks/**/*'

Documentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false
  # EnforcedStyle: compact
  # SupportedStyles:
  #   - nested
  #   - compact

Style/FrozenStringLiteralComment:
  Enabled: false
